# Generated by Django 3.2 on 2023-04-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('crud', '0003_alter_listingmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='reservation',
            field=models.ManyToManyField(related_name='reservation', to='reservations.Reservations'),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('approved', 'approved'), ('pending cancellation', 'pending cancellation'), ('available', 'available')], default='available', max_length=20, null=True),
        ),
    ]
