# Generated by Django 3.2 on 2023-04-20 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crud', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('denied', 'denied'), ('approved', 'approved'), ('expired', 'expired'), ('pending cancellation', 'pending cancellation'), ('canceled', 'canceled'), ('terminated', 'terminated'), ('completed', 'completed')], default='pending', max_length=20, null=True)),
                ('reserved_for', models.DateField()),
                ('approve_in', models.IntegerField()),
                ('reserved_at', models.DateField(auto_now_add=True)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_set', to='crud.listingmodel')),
            ],
        ),
    ]
