# Generated by Django 3.2 on 2023-04-21 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='reserved_for',
            new_name='reserved_from',
        ),
        migrations.AddField(
            model_name='reservations',
            name='num_guests',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservations',
            name='reserved_to',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
